title: Restless Point

permalink: /:categories/:title/
future: true
kramdown:
   input: GFM
   hard_wrap: false
gfm_quirks: paragraph_end
# repository: xslim/restlesspoint.com

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-avatar
  - jekyll-default-layout
  - jekyll-github-metadata
  - jekyll-readme-index
  - jekyll-titles-from-headings

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

readme_index:
  enabled:          true
  remove_originals: true

logo: logo-50.png
disqus_shortname: restlesspoint



# Owner/author information
owner:
  name:           Restlesss Point
  avatar:         taras-kalapun-photo.jpg
  bio:
  email:          t@kalapun.com
  twitter:
  instagram:
  github:
  facebook:

# feed: http://feeds.feedburner.com/RestlessPoint

google_analytics: UA-2087894-20
google_verify:

# Internal pages/posts to include in top navigation
links:
  - title: Travel
    url: /travel/
  - title: Spots
    url: /spots/
  - title: Articles
    url: /articles/
  - title: About
    url: /about/

# Map
map:
  type: 'leaflet'
  zoom: 12
  map_as_feature: true
  google_api_key: AIzaSyAwvfaem3xhKaM0pZSj0P_TcuRRaNbB6RA
